openapi: 3.0.0


info:
 version: '1.0'
 title: 'LBAW MediaLibrary Web API'
 description: 'Web Resources Specification (A7) for SWC News'

servers:
- url: http://lbaw.fe.up.pt
 description: Production server

externalDocs:
 description: Find more info here.
 url: https://web.fe.up.pt/~ssn/wiki/teach/lbaw/medialib/a07

tags:
 - name: 'M01: Authentication and Indivual Profile'
 - name: 'M02: Posts and Comments'
 - name: 'M03: Users'
 - name: 'M04: Feed and Search'
 - name: 'M05: Notifications'